name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 11.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          artifactErrorsFailBuild: true
          removeArtifacts: false
          replacesArtifacts: false
          artifacts: "package.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
